# What do we want
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  # Link to PV -> label, access & size will be checked!!
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce # Volume should be mounted by a single node
  resources:
    requests:
      storage: 7Gi

---
# How do we want it to be implemented (in Kubernetes Cluster -> can be local Minikube VM or in cloud)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2







